import type { EditorColorScheme } from '../types/editorScheme';

export const catppuccinMocha: EditorColorScheme = {
  id: 'catppuccin-mocha',
  name: 'Catppuccin Mocha',
  type: 'dark',
  monacoTheme: {
    base: 'vs-dark',
    inherit: false,
    rules: [
      { token: '', foreground: 'CDD6F4', background: '1E1E2E' },
      // Comments
      { token: 'comment', foreground: '6C7086', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '6C7086', fontStyle: 'italic' },
      // Keywords
      { token: 'keyword', foreground: 'CBA6F7' },
      { token: 'keyword.if', foreground: 'CBA6F7' },
      { token: 'keyword.else', foreground: 'CBA6F7' },
      { token: 'keyword.for', foreground: 'CBA6F7' },
      { token: 'keyword.while', foreground: 'CBA6F7' },
      { token: 'keyword.return', foreground: 'CBA6F7' },
      { token: 'keyword.break', foreground: 'CBA6F7' },
      { token: 'keyword.continue', foreground: 'CBA6F7' },
      { token: 'keyword.switch', foreground: 'CBA6F7' },
      { token: 'keyword.try', foreground: 'CBA6F7' },
      { token: 'keyword.catch', foreground: 'CBA6F7' },
      { token: 'keyword.throw', foreground: 'CBA6F7' },
      // Preprocessor
      { token: 'keyword.directive', foreground: 'F5C2E7', fontStyle: 'bold' },
      { token: 'keyword.directive.include', foreground: 'F5C2E7', fontStyle: 'bold' },
      { token: 'string.include.identifier', foreground: 'A6E3A1' },
      // Identifiers
      { token: 'identifier', foreground: 'CDD6F4' },
      // Strings
      { token: 'string', foreground: 'A6E3A1' },
      { token: 'string.escape', foreground: 'F5C2E7' },
      { token: 'string.raw', foreground: 'A6E3A1' },
      { token: 'string.invalid', foreground: 'F38BA8' },
      { token: 'character', foreground: 'A6E3A1' },
      // Numbers
      { token: 'number', foreground: 'FAB387' },
      { token: 'number.float', foreground: 'FAB387' },
      { token: 'number.hex', foreground: 'FAB387' },
      { token: 'number.binary', foreground: 'FAB387' },
      { token: 'number.octal', foreground: 'FAB387' },
      // Delimiters
      { token: 'delimiter', foreground: '9399B2' },
      { token: 'delimiter.curly', foreground: '9399B2' },
      { token: 'delimiter.parenthesis', foreground: '9399B2' },
      { token: 'delimiter.angle', foreground: '9399B2' },
      { token: 'delimiter.square', foreground: '9399B2' },
      // Annotations
      { token: 'annotation', foreground: 'F5C2E7' },
      // Regex
      { token: 'regexp', foreground: 'F5C2E7' },
      // Invalid
      { token: 'invalid', foreground: 'F38BA8', fontStyle: 'underline' },
      // TextMate fallbacks
      { token: 'type', foreground: 'F9E2AF' },
      { token: 'type.identifier', foreground: 'F9E2AF' },
      { token: 'keyword.control', foreground: 'CBA6F7' },
      { token: 'keyword.operator', foreground: '89DCEB' },
      { token: 'storage', foreground: 'CBA6F7' },
      { token: 'storage.type', foreground: 'F38BA8' },
      { token: 'constant', foreground: 'FAB387' },
      { token: 'entity.name.function', foreground: '89B4FA' },
      { token: 'support.function', foreground: '89B4FA' },
      { token: 'entity.name.type', foreground: 'F9E2AF' },
      { token: 'variable', foreground: 'CDD6F4' },
      { token: 'variable.parameter', foreground: 'EBA0AC', fontStyle: 'italic' },
      { token: 'tag', foreground: 'CBA6F7' },
      { token: 'attribute.name', foreground: '89B4FA' },
      { token: 'attribute.value', foreground: 'A6E3A1' },
      { token: 'namespace', foreground: 'F9E2AF', fontStyle: 'italic' },
      { token: 'white', foreground: '313244' },
    ],
    colors: {
      'editor.background': '#1E1E2E',
      'editor.foreground': '#CDD6F4',
      'editor.lineHighlightBackground': '#313244',
      'editor.selectionBackground': '#45475A',
      'editor.inactiveSelectionBackground': '#45475A80',
      'editor.selectionHighlightBackground': '#45475A50',
      'editor.wordHighlightBackground': '#45475ACC',
      'editor.wordHighlightStrongBackground': '#89B4FA40',
      'editor.findMatchBackground': '#F9E2AF40',
      'editor.findMatchHighlightBackground': '#F9E2AF25',
      'editorBracketMatch.background': '#45475A80',
      'editorBracketMatch.border': '#F9E2AF',
      'editorIndentGuide.background': '#313244',
      'editorIndentGuide.activeBackground': '#585B70',
      'editorCursor.foreground': '#F5E0DC',
      'editorLineNumber.foreground': '#585B70',
      'editorLineNumber.activeForeground': '#CDD6F4',
      'editorError.foreground': '#F38BA8',
      'editorWarning.foreground': '#FAB387',
      'editorInfo.foreground': '#89B4FA',
      'editorGutter.background': '#1E1E2E',
      'editorWidget.background': '#181825',
      'editorWidget.border': '#45475A',
      'editorSuggestWidget.background': '#181825',
      'editorSuggestWidget.border': '#45475A',
      'editorSuggestWidget.foreground': '#CDD6F4',
      'editorSuggestWidget.selectedBackground': '#313244',
      'editorSuggestWidget.selectedForeground': '#CDD6F4',
      'editorSuggestWidget.highlightForeground': '#89B4FA',
      'editorHoverWidget.background': '#1E1E2E',
      'editorHoverWidget.border': '#45475A',
      'editorHoverWidget.foreground': '#CDD6F4',
      'input.background': '#181825',
      'input.border': '#45475A',
      'input.foreground': '#CDD6F4',
      'input.placeholderForeground': '#6C7086',
      'scrollbar.shadow': '#00000050',
      'scrollbarSlider.background': '#585B7066',
      'scrollbarSlider.hoverBackground': '#585B70B3',
      'scrollbarSlider.activeBackground': '#6C7086',
      'minimap.background': '#1E1E2E',
      'editorOverviewRuler.border': '#45475A',
      'editorWhitespace.foreground': '#313244',
      'editorRuler.foreground': '#313244',
      'editorBracketHighlight.foreground1': '#F38BA8',
      'editorBracketHighlight.foreground2': '#FAB387',
      'editorBracketHighlight.foreground3': '#F9E2AF',
      'editorBracketHighlight.foreground4': '#A6E3A1',
      'editorBracketHighlight.foreground5': '#89B4FA',
      'editorBracketHighlight.foreground6': '#CBA6F7',
    },
  },
};
