import type { EditorColorScheme } from '../types/editorScheme';

export const draculaScheme: EditorColorScheme = {
  id: 'dracula-scheme',
  name: 'Dracula',
  type: 'dark',
  monacoTheme: {
    base: 'vs-dark',
    inherit: false,
    rules: [
      { token: '', foreground: 'F8F8F2', background: '282A36' },
      // Comments
      { token: 'comment', foreground: '6272A4', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '6272A4', fontStyle: 'italic' },
      // Keywords
      { token: 'keyword', foreground: 'FF79C6' },
      { token: 'keyword.if', foreground: 'FF79C6' },
      { token: 'keyword.else', foreground: 'FF79C6' },
      { token: 'keyword.for', foreground: 'FF79C6' },
      { token: 'keyword.while', foreground: 'FF79C6' },
      { token: 'keyword.return', foreground: 'FF79C6' },
      { token: 'keyword.break', foreground: 'FF79C6' },
      { token: 'keyword.continue', foreground: 'FF79C6' },
      { token: 'keyword.switch', foreground: 'FF79C6' },
      { token: 'keyword.try', foreground: 'FF79C6' },
      { token: 'keyword.catch', foreground: 'FF79C6' },
      { token: 'keyword.throw', foreground: 'FF79C6' },
      // Preprocessor
      { token: 'keyword.directive', foreground: 'FF79C6', fontStyle: 'bold' },
      { token: 'keyword.directive.include', foreground: 'FF79C6', fontStyle: 'bold' },
      { token: 'string.include.identifier', foreground: 'F1FA8C' },
      // Identifiers
      { token: 'identifier', foreground: 'F8F8F2' },
      // Strings
      { token: 'string', foreground: 'F1FA8C' },
      { token: 'string.escape', foreground: 'FF79C6' },
      { token: 'string.raw', foreground: 'F1FA8C' },
      { token: 'string.invalid', foreground: 'FF5555' },
      { token: 'character', foreground: 'F1FA8C' },
      // Numbers
      { token: 'number', foreground: 'BD93F9' },
      { token: 'number.float', foreground: 'BD93F9' },
      { token: 'number.hex', foreground: 'BD93F9' },
      { token: 'number.binary', foreground: 'BD93F9' },
      { token: 'number.octal', foreground: 'BD93F9' },
      // Delimiters
      { token: 'delimiter', foreground: 'F8F8F2' },
      { token: 'delimiter.curly', foreground: 'F8F8F2' },
      { token: 'delimiter.parenthesis', foreground: 'F8F8F2' },
      { token: 'delimiter.angle', foreground: 'F8F8F2' },
      { token: 'delimiter.square', foreground: 'F8F8F2' },
      // Annotations
      { token: 'annotation', foreground: 'FF79C6' },
      // Regex
      { token: 'regexp', foreground: 'F1FA8C' },
      // Invalid
      { token: 'invalid', foreground: 'FF5555', fontStyle: 'underline' },
      // TextMate fallbacks
      { token: 'type', foreground: '8BE9FD', fontStyle: 'italic' },
      { token: 'type.identifier', foreground: '8BE9FD', fontStyle: 'italic' },
      { token: 'keyword.control', foreground: 'FF79C6' },
      { token: 'storage', foreground: 'FF79C6' },
      { token: 'storage.type', foreground: '8BE9FD', fontStyle: 'italic' },
      { token: 'constant', foreground: 'BD93F9' },
      { token: 'entity.name.function', foreground: '50FA7B' },
      { token: 'support.function', foreground: '50FA7B' },
      { token: 'entity.name.type', foreground: '8BE9FD', fontStyle: 'italic' },
      { token: 'variable', foreground: 'F8F8F2' },
      { token: 'variable.parameter', foreground: 'FFB86C', fontStyle: 'italic' },
      { token: 'tag', foreground: 'FF79C6' },
      { token: 'attribute.name', foreground: '50FA7B' },
      { token: 'attribute.value', foreground: 'F1FA8C' },
      { token: 'namespace', foreground: '8BE9FD', fontStyle: 'italic' },
      { token: 'white', foreground: '44475A' },
    ],
    colors: {
      'editor.background': '#282A36',
      'editor.foreground': '#F8F8F2',
      'editor.lineHighlightBackground': '#44475A75',
      'editor.selectionBackground': '#44475A',
      'editor.inactiveSelectionBackground': '#44475A80',
      'editor.selectionHighlightBackground': '#44475A50',
      'editor.wordHighlightBackground': '#8BE9FD50',
      'editor.wordHighlightStrongBackground': '#50FA7B50',
      'editor.findMatchBackground': '#FFB86C80',
      'editor.findMatchHighlightBackground': '#FFB86C40',
      'editorBracketMatch.background': '#44475A',
      'editorBracketMatch.border': '#F1FA8C',
      'editorIndentGuide.background': '#44475A70',
      'editorIndentGuide.activeBackground': '#6272A4',
      'editorCursor.foreground': '#F8F8F2',
      'editorLineNumber.foreground': '#6272A4',
      'editorLineNumber.activeForeground': '#F8F8F2',
      'editorError.foreground': '#FF5555',
      'editorWarning.foreground': '#FFB86C',
      'editorInfo.foreground': '#8BE9FD',
      'editorGutter.background': '#282A36',
      'editorWidget.background': '#21222C',
      'editorWidget.border': '#6272A4',
      'editorSuggestWidget.background': '#21222C',
      'editorSuggestWidget.border': '#6272A4',
      'editorSuggestWidget.foreground': '#F8F8F2',
      'editorSuggestWidget.selectedBackground': '#44475A',
      'editorSuggestWidget.selectedForeground': '#F8F8F2',
      'editorSuggestWidget.highlightForeground': '#8BE9FD',
      'editorHoverWidget.background': '#282A36',
      'editorHoverWidget.border': '#6272A4',
      'editorHoverWidget.foreground': '#F8F8F2',
      'input.background': '#282A36',
      'input.border': '#6272A4',
      'input.foreground': '#F8F8F2',
      'input.placeholderForeground': '#6272A4',
      'scrollbar.shadow': '#00000050',
      'scrollbarSlider.background': '#44475A80',
      'scrollbarSlider.hoverBackground': '#44475ACC',
      'scrollbarSlider.activeBackground': '#44475AFF',
      'minimap.background': '#282A36',
      'editorOverviewRuler.border': '#44475A',
      'editorWhitespace.foreground': '#44475A',
      'editorRuler.foreground': '#44475A',
      'editorBracketHighlight.foreground1': '#F1FA8C',
      'editorBracketHighlight.foreground2': '#FF79C6',
      'editorBracketHighlight.foreground3': '#8BE9FD',
      'editorBracketHighlight.foreground4': '#50FA7B',
      'editorBracketHighlight.foreground5': '#BD93F9',
      'editorBracketHighlight.foreground6': '#FFB86C',
    },
  },
};
