import type { EditorColorScheme } from '../types/editorScheme';

export const githubDark: EditorColorScheme = {
  id: 'github-dark',
  name: 'GitHub Dark',
  type: 'dark',
  monacoTheme: {
    base: 'vs-dark',
    inherit: false,
    rules: [
      { token: '', foreground: 'C9D1D9', background: '0D1117' },
      // Comments
      { token: 'comment', foreground: '8B949E', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '8B949E', fontStyle: 'italic' },
      // Keywords
      { token: 'keyword', foreground: 'FF7B72' },
      { token: 'keyword.if', foreground: 'FF7B72' },
      { token: 'keyword.else', foreground: 'FF7B72' },
      { token: 'keyword.for', foreground: 'FF7B72' },
      { token: 'keyword.while', foreground: 'FF7B72' },
      { token: 'keyword.return', foreground: 'FF7B72' },
      { token: 'keyword.break', foreground: 'FF7B72' },
      { token: 'keyword.continue', foreground: 'FF7B72' },
      { token: 'keyword.switch', foreground: 'FF7B72' },
      { token: 'keyword.try', foreground: 'FF7B72' },
      { token: 'keyword.catch', foreground: 'FF7B72' },
      { token: 'keyword.throw', foreground: 'FF7B72' },
      // Preprocessor
      { token: 'keyword.directive', foreground: 'FF7B72', fontStyle: 'bold' },
      { token: 'keyword.directive.include', foreground: 'FF7B72', fontStyle: 'bold' },
      { token: 'string.include.identifier', foreground: 'A5D6FF' },
      // Identifiers
      { token: 'identifier', foreground: 'C9D1D9' },
      // Strings
      { token: 'string', foreground: 'A5D6FF' },
      { token: 'string.escape', foreground: '79C0FF' },
      { token: 'string.raw', foreground: 'A5D6FF' },
      { token: 'string.invalid', foreground: 'F85149' },
      { token: 'character', foreground: 'A5D6FF' },
      // Numbers
      { token: 'number', foreground: '79C0FF' },
      { token: 'number.float', foreground: '79C0FF' },
      { token: 'number.hex', foreground: '79C0FF' },
      { token: 'number.binary', foreground: '79C0FF' },
      { token: 'number.octal', foreground: '79C0FF' },
      // Delimiters
      { token: 'delimiter', foreground: 'C9D1D9' },
      { token: 'delimiter.curly', foreground: 'C9D1D9' },
      { token: 'delimiter.parenthesis', foreground: 'C9D1D9' },
      { token: 'delimiter.angle', foreground: 'C9D1D9' },
      { token: 'delimiter.square', foreground: 'C9D1D9' },
      // Annotations
      { token: 'annotation', foreground: 'FF7B72' },
      // Regex
      { token: 'regexp', foreground: 'A5D6FF' },
      // Invalid
      { token: 'invalid', foreground: 'F85149', fontStyle: 'underline' },
      // TextMate fallbacks
      { token: 'type', foreground: 'FFA657' },
      { token: 'type.identifier', foreground: 'FFA657' },
      { token: 'keyword.control', foreground: 'FF7B72' },
      { token: 'storage', foreground: 'FF7B72' },
      { token: 'constant', foreground: '79C0FF' },
      { token: 'entity.name.function', foreground: 'D2A8FF' },
      { token: 'support.function', foreground: 'D2A8FF' },
      { token: 'entity.name.type', foreground: 'FFA657' },
      { token: 'variable', foreground: 'FFA657' },
      { token: 'variable.parameter', foreground: 'FFA657', fontStyle: 'italic' },
      { token: 'tag', foreground: '7EE787' },
      { token: 'attribute.name', foreground: '79C0FF' },
      { token: 'attribute.value', foreground: 'A5D6FF' },
      { token: 'namespace', foreground: 'FFA657', fontStyle: 'italic' },
      { token: 'white', foreground: '21262D' },
    ],
    colors: {
      'editor.background': '#0D1117',
      'editor.foreground': '#C9D1D9',
      'editor.lineHighlightBackground': '#161B22',
      'editor.selectionBackground': '#264F78',
      'editor.inactiveSelectionBackground': '#264F7880',
      'editor.selectionHighlightBackground': '#3FB95040',
      'editor.wordHighlightBackground': '#3FB95030',
      'editor.wordHighlightStrongBackground': '#3FB95050',
      'editor.findMatchBackground': '#9E6A03AA',
      'editor.findMatchHighlightBackground': '#F2CC6044',
      'editorBracketMatch.background': '#3FB95040',
      'editorBracketMatch.border': '#3FB950',
      'editorIndentGuide.background': '#21262D',
      'editorIndentGuide.activeBackground': '#30363D',
      'editorCursor.foreground': '#C9D1D9',
      'editorLineNumber.foreground': '#484F58',
      'editorLineNumber.activeForeground': '#C9D1D9',
      'editorError.foreground': '#F85149',
      'editorWarning.foreground': '#D29922',
      'editorInfo.foreground': '#58A6FF',
      'editorGutter.background': '#0D1117',
      'editorWidget.background': '#161B22',
      'editorWidget.border': '#30363D',
      'editorSuggestWidget.background': '#161B22',
      'editorSuggestWidget.border': '#30363D',
      'editorSuggestWidget.foreground': '#C9D1D9',
      'editorSuggestWidget.selectedBackground': '#1F6FEB33',
      'editorSuggestWidget.selectedForeground': '#C9D1D9',
      'editorSuggestWidget.highlightForeground': '#58A6FF',
      'editorHoverWidget.background': '#161B22',
      'editorHoverWidget.border': '#30363D',
      'editorHoverWidget.foreground': '#C9D1D9',
      'input.background': '#0D1117',
      'input.border': '#30363D',
      'input.foreground': '#C9D1D9',
      'input.placeholderForeground': '#484F58',
      'scrollbar.shadow': '#00000050',
      'scrollbarSlider.background': '#484F5866',
      'scrollbarSlider.hoverBackground': '#484F58B3',
      'scrollbarSlider.activeBackground': '#6E7681',
      'minimap.background': '#0D1117',
      'editorOverviewRuler.border': '#30363D',
      'editorWhitespace.foreground': '#21262D',
      'editorRuler.foreground': '#21262D',
      'editorBracketHighlight.foreground1': '#79C0FF',
      'editorBracketHighlight.foreground2': '#D2A8FF',
      'editorBracketHighlight.foreground3': 'FFA657',
      'editorBracketHighlight.foreground4': '#79C0FF',
      'editorBracketHighlight.foreground5': '#D2A8FF',
      'editorBracketHighlight.foreground6': '#FFA657',
    },
  },
};
