import type { EditorColorScheme } from '../types/editorScheme';

export const monokaiPro: EditorColorScheme = {
  id: 'monokai-pro',
  name: 'Monokai Pro',
  type: 'dark',
  monacoTheme: {
    base: 'vs-dark',
    inherit: false,
    rules: [
      { token: '', foreground: 'F8F8F2', background: '272822' },
      // Comments
      { token: 'comment', foreground: '75715E', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '75715E', fontStyle: 'italic' },
      // Keywords
      { token: 'keyword', foreground: 'F92672' },
      { token: 'keyword.if', foreground: 'F92672' },
      { token: 'keyword.else', foreground: 'F92672' },
      { token: 'keyword.for', foreground: 'F92672' },
      { token: 'keyword.while', foreground: 'F92672' },
      { token: 'keyword.return', foreground: 'F92672' },
      { token: 'keyword.break', foreground: 'F92672' },
      { token: 'keyword.continue', foreground: 'F92672' },
      { token: 'keyword.switch', foreground: 'F92672' },
      { token: 'keyword.try', foreground: 'F92672' },
      { token: 'keyword.catch', foreground: 'F92672' },
      { token: 'keyword.throw', foreground: 'F92672' },
      // Preprocessor
      { token: 'keyword.directive', foreground: 'F92672', fontStyle: 'bold' },
      { token: 'keyword.directive.include', foreground: 'F92672', fontStyle: 'bold' },
      { token: 'string.include.identifier', foreground: 'E6DB74' },
      // Identifiers
      { token: 'identifier', foreground: 'F8F8F2' },
      // Strings
      { token: 'string', foreground: 'E6DB74' },
      { token: 'string.escape', foreground: 'AE81FF' },
      { token: 'string.raw', foreground: 'E6DB74' },
      { token: 'string.invalid', foreground: 'F92672' },
      { token: 'character', foreground: 'E6DB74' },
      // Numbers
      { token: 'number', foreground: 'AE81FF' },
      { token: 'number.float', foreground: 'AE81FF' },
      { token: 'number.hex', foreground: 'AE81FF' },
      { token: 'number.binary', foreground: 'AE81FF' },
      { token: 'number.octal', foreground: 'AE81FF' },
      // Delimiters
      { token: 'delimiter', foreground: 'F8F8F2' },
      { token: 'delimiter.curly', foreground: 'F8F8F2' },
      { token: 'delimiter.parenthesis', foreground: 'F8F8F2' },
      { token: 'delimiter.angle', foreground: 'F8F8F2' },
      { token: 'delimiter.square', foreground: 'F8F8F2' },
      // Annotations
      { token: 'annotation', foreground: 'F92672' },
      // Regex
      { token: 'regexp', foreground: 'E6DB74' },
      // Invalid
      { token: 'invalid', foreground: 'F8F8F2', background: 'F92672' },
      // TextMate fallbacks
      { token: 'type', foreground: '66D9EF', fontStyle: 'italic' },
      { token: 'type.identifier', foreground: '66D9EF', fontStyle: 'italic' },
      { token: 'keyword.control', foreground: 'F92672' },
      { token: 'storage', foreground: 'F92672' },
      { token: 'storage.type', foreground: '66D9EF', fontStyle: 'italic' },
      { token: 'constant', foreground: 'AE81FF' },
      { token: 'entity.name.function', foreground: 'A6E22E' },
      { token: 'support.function', foreground: 'A6E22E' },
      { token: 'entity.name.type', foreground: '66D9EF', fontStyle: 'italic' },
      { token: 'variable', foreground: 'F8F8F2' },
      { token: 'variable.parameter', foreground: 'FD971F', fontStyle: 'italic' },
      { token: 'tag', foreground: 'F92672' },
      { token: 'attribute.name', foreground: 'A6E22E' },
      { token: 'attribute.value', foreground: 'E6DB74' },
      { token: 'namespace', foreground: '66D9EF', fontStyle: 'italic' },
      { token: 'white', foreground: '464741' },
    ],
    colors: {
      'editor.background': '#272822',
      'editor.foreground': '#F8F8F2',
      'editor.lineHighlightBackground': '#3E3D32',
      'editor.selectionBackground': '#49483E',
      'editor.inactiveSelectionBackground': '#49483E80',
      'editor.selectionHighlightBackground': '#49483E60',
      'editor.wordHighlightBackground': '#49483ECC',
      'editor.wordHighlightStrongBackground': '#49483ECC',
      'editor.findMatchBackground': '#FFE79240',
      'editor.findMatchHighlightBackground': '#FFE79220',
      'editorBracketMatch.background': '#3E3D3280',
      'editorBracketMatch.border': '#888888',
      'editorIndentGuide.background': '#464741',
      'editorIndentGuide.activeBackground': '#767771',
      'editorCursor.foreground': '#F8F8F0',
      'editorLineNumber.foreground': '#90908A',
      'editorLineNumber.activeForeground': '#C2C2BF',
      'editorError.foreground': '#F92672',
      'editorWarning.foreground': '#FD971F',
      'editorInfo.foreground': '#66D9EF',
      'editorGutter.background': '#272822',
      'editorWidget.background': '#1E1F1C',
      'editorWidget.border': '#75715E',
      'editorSuggestWidget.background': '#272822',
      'editorSuggestWidget.border': '#75715E',
      'editorSuggestWidget.foreground': '#F8F8F2',
      'editorSuggestWidget.selectedBackground': '#3E3D32',
      'editorSuggestWidget.selectedForeground': '#F8F8F2',
      'editorSuggestWidget.highlightForeground': '#A6E22E',
      'editorHoverWidget.background': '#272822',
      'editorHoverWidget.border': '#75715E',
      'editorHoverWidget.foreground': '#F8F8F2',
      'input.background': '#1E1F1C',
      'input.border': '#75715E',
      'input.foreground': '#F8F8F2',
      'input.placeholderForeground': '#75715E',
      'scrollbar.shadow': '#00000050',
      'scrollbarSlider.background': '#49483E80',
      'scrollbarSlider.hoverBackground': '#49483ECC',
      'scrollbarSlider.activeBackground': '#49483EFF',
      'minimap.background': '#272822',
      'editorOverviewRuler.border': '#75715E30',
      'editorWhitespace.foreground': '#464741',
      'editorRuler.foreground': '#464741',
      'editorBracketHighlight.foreground1': '#F92672',
      'editorBracketHighlight.foreground2': '#A6E22E',
      'editorBracketHighlight.foreground3': '#66D9EF',
      'editorBracketHighlight.foreground4': '#AE81FF',
      'editorBracketHighlight.foreground5': '#E6DB74',
      'editorBracketHighlight.foreground6': '#FD971F',
    },
  },
};
