import type { EditorColorScheme } from '../types/editorScheme';

export const oneDarkPro: EditorColorScheme = {
  id: 'one-dark-pro',
  name: 'One Dark Pro',
  type: 'dark',
  monacoTheme: {
    base: 'vs-dark',
    inherit: false,
    rules: [
      { token: '', foreground: 'ABB2BF', background: '282C34' },
      // Comments
      { token: 'comment', foreground: '5C6370', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '5C6370', fontStyle: 'italic' },
      // Keywords
      { token: 'keyword', foreground: 'C678DD' },
      { token: 'keyword.if', foreground: 'C678DD' },
      { token: 'keyword.else', foreground: 'C678DD' },
      { token: 'keyword.for', foreground: 'C678DD' },
      { token: 'keyword.while', foreground: 'C678DD' },
      { token: 'keyword.return', foreground: 'C678DD' },
      { token: 'keyword.break', foreground: 'C678DD' },
      { token: 'keyword.continue', foreground: 'C678DD' },
      { token: 'keyword.switch', foreground: 'C678DD' },
      { token: 'keyword.try', foreground: 'C678DD' },
      { token: 'keyword.catch', foreground: 'C678DD' },
      { token: 'keyword.throw', foreground: 'C678DD' },
      // Preprocessor
      { token: 'keyword.directive', foreground: 'C678DD', fontStyle: 'bold' },
      { token: 'keyword.directive.include', foreground: 'C678DD', fontStyle: 'bold' },
      { token: 'string.include.identifier', foreground: '98C379' },
      // Identifiers
      { token: 'identifier', foreground: 'ABB2BF' },
      // Strings
      { token: 'string', foreground: '98C379' },
      { token: 'string.escape', foreground: '56B6C2' },
      { token: 'string.raw', foreground: '98C379' },
      { token: 'string.invalid', foreground: 'E06C75' },
      { token: 'character', foreground: '98C379' },
      // Numbers
      { token: 'number', foreground: 'D19A66' },
      { token: 'number.float', foreground: 'D19A66' },
      { token: 'number.hex', foreground: 'D19A66' },
      { token: 'number.binary', foreground: 'D19A66' },
      { token: 'number.octal', foreground: 'D19A66' },
      // Delimiters
      { token: 'delimiter', foreground: 'ABB2BF' },
      { token: 'delimiter.curly', foreground: 'ABB2BF' },
      { token: 'delimiter.parenthesis', foreground: 'ABB2BF' },
      { token: 'delimiter.angle', foreground: 'ABB2BF' },
      { token: 'delimiter.square', foreground: 'ABB2BF' },
      // Annotations
      { token: 'annotation', foreground: 'C678DD' },
      // Regex
      { token: 'regexp', foreground: '98C379' },
      // Invalid
      { token: 'invalid', foreground: 'F44747', fontStyle: 'underline' },
      // TextMate fallbacks
      { token: 'type', foreground: 'E5C07B' },
      { token: 'type.identifier', foreground: 'E5C07B' },
      { token: 'keyword.control', foreground: 'C678DD' },
      { token: 'keyword.operator', foreground: '56B6C2' },
      { token: 'storage', foreground: 'C678DD' },
      { token: 'constant', foreground: 'D19A66' },
      { token: 'entity.name.function', foreground: '61AFEF' },
      { token: 'support.function', foreground: '61AFEF' },
      { token: 'entity.name.type', foreground: 'E5C07B' },
      { token: 'variable', foreground: 'E06C75' },
      { token: 'variable.parameter', foreground: 'E06C75', fontStyle: 'italic' },
      { token: 'tag', foreground: 'E06C75' },
      { token: 'attribute.name', foreground: 'D19A66' },
      { token: 'attribute.value', foreground: '98C379' },
      { token: 'namespace', foreground: 'E5C07B', fontStyle: 'italic' },
      { token: 'white', foreground: '3B4048' },
    ],
    colors: {
      'editor.background': '#282C34',
      'editor.foreground': '#ABB2BF',
      'editor.lineHighlightBackground': '#2C313C',
      'editor.selectionBackground': '#3E4451',
      'editor.inactiveSelectionBackground': '#3E445180',
      'editor.selectionHighlightBackground': '#3E445150',
      'editor.wordHighlightBackground': '#484E5B80',
      'editor.wordHighlightStrongBackground': '#61AFEF30',
      'editor.findMatchBackground': '#D19A6644',
      'editor.findMatchHighlightBackground': '#D19A6633',
      'editorBracketMatch.background': '#2C313C',
      'editorBracketMatch.border': '#528BFF',
      'editorIndentGuide.background': '#3B4048',
      'editorIndentGuide.activeBackground': '#636B78',
      'editorCursor.foreground': '#528BFF',
      'editorLineNumber.foreground': '#495162',
      'editorLineNumber.activeForeground': '#ABB2BF',
      'editorError.foreground': '#E06C75',
      'editorWarning.foreground': '#D19A66',
      'editorInfo.foreground': '#61AFEF',
      'editorGutter.background': '#282C34',
      'editorWidget.background': '#21252B',
      'editorWidget.border': '#3A3F4B',
      'editorSuggestWidget.background': '#21252B',
      'editorSuggestWidget.border': '#3A3F4B',
      'editorSuggestWidget.foreground': '#ABB2BF',
      'editorSuggestWidget.selectedBackground': '#2C313C',
      'editorSuggestWidget.selectedForeground': '#ABB2BF',
      'editorSuggestWidget.highlightForeground': '#61AFEF',
      'editorHoverWidget.background': '#21252B',
      'editorHoverWidget.border': '#3A3F4B',
      'editorHoverWidget.foreground': '#ABB2BF',
      'input.background': '#1D2025',
      'input.border': '#3A3F4B',
      'input.foreground': '#ABB2BF',
      'input.placeholderForeground': '#5C6370',
      'scrollbar.shadow': '#00000030',
      'scrollbarSlider.background': '#4E566680',
      'scrollbarSlider.hoverBackground': '#5A637580',
      'scrollbarSlider.activeBackground': '#747D9180',
      'minimap.background': '#282C34',
      'editorOverviewRuler.border': '#3A3F4B40',
      'editorWhitespace.foreground': '#3B4048',
      'editorRuler.foreground': '#3B4048',
      'editorBracketHighlight.foreground1': '#D19A66',
      'editorBracketHighlight.foreground2': '#C678DD',
      'editorBracketHighlight.foreground3': '#61AFEF',
      'editorBracketHighlight.foreground4': '#D19A66',
      'editorBracketHighlight.foreground5': '#C678DD',
      'editorBracketHighlight.foreground6': '#61AFEF',
    },
  },
};
