import type { EditorColorScheme } from '../types/editorScheme';

export const vscodeDarkPlusPlus: EditorColorScheme = {
  id: 'vscode-dark-plus-plus',
  name: 'Night Dark Mode',
  type: 'dark',
  monacoTheme: {
    base: 'vs-dark',
    inherit: false,
    rules: [
      // Default
      { token: '', foreground: 'D8D6CF', background: '090A0D' },
      // Comments
      { token: 'comment', foreground: '6C7D67', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '6C7D67', fontStyle: 'italic' },
      // Keywords
      { token: 'keyword', foreground: 'BFA4E8' },
      { token: 'keyword.if', foreground: 'C79BE8' },
      { token: 'keyword.else', foreground: 'C79BE8' },
      { token: 'keyword.for', foreground: 'C79BE8' },
      { token: 'keyword.while', foreground: 'C79BE8' },
      { token: 'keyword.do', foreground: 'C79BE8' },
      { token: 'keyword.switch', foreground: 'C79BE8' },
      { token: 'keyword.case', foreground: 'C79BE8' },
      { token: 'keyword.return', foreground: 'C79BE8' },
      { token: 'keyword.break', foreground: 'C79BE8' },
      { token: 'keyword.continue', foreground: 'C79BE8' },
      { token: 'keyword.try', foreground: 'C79BE8' },
      { token: 'keyword.catch', foreground: 'C79BE8' },
      { token: 'keyword.throw', foreground: 'C79BE8' },
      { token: 'keyword.goto', foreground: 'C79BE8' },
      // Preprocessor directives
      { token: 'keyword.directive', foreground: 'C79BE8' },
      { token: 'keyword.directive.include', foreground: 'C79BE8' },
      { token: 'string.include.identifier', foreground: 'D5A67A' },
      // Identifiers
      { token: 'identifier', foreground: 'CDBFA2' },
      // Strings
      { token: 'string', foreground: 'D5A67A' },
      { token: 'string.escape', foreground: 'E2C48D' },
      { token: 'string.raw', foreground: 'D5A67A' },
      { token: 'string.invalid', foreground: 'E26A6A' },
      { token: 'character', foreground: 'D5A67A' },
      // Numbers
      { token: 'number', foreground: 'AAC18C' },
      { token: 'number.float', foreground: 'AAC18C' },
      { token: 'number.hex', foreground: 'AAC18C' },
      { token: 'number.binary', foreground: 'AAC18C' },
      { token: 'number.octal', foreground: 'AAC18C' },
      // Operators and delimiters
      { token: 'delimiter', foreground: 'D8D6CF' },
      { token: 'delimiter.curly', foreground: 'D8D6CF' },
      { token: 'delimiter.parenthesis', foreground: 'D8D6CF' },
      { token: 'delimiter.angle', foreground: 'D8D6CF' },
      { token: 'delimiter.square', foreground: 'D8D6CF' },
      // Annotation
      { token: 'annotation', foreground: 'C79BE8' },
      // Regex
      { token: 'regexp', foreground: 'CE8770' },
      // Invalid
      { token: 'invalid', foreground: 'E26A6A', fontStyle: 'underline' },
      // TextMate-style tokens
      { token: 'type', foreground: '82B08D' },
      { token: 'type.identifier', foreground: '82B08D' },
      { token: 'keyword.control', foreground: 'C79BE8' },
      { token: 'storage', foreground: 'B6A1D8' },
      { token: 'storage.type', foreground: 'B6A1D8' },
      { token: 'constant', foreground: 'D7C28B' },
      { token: 'constant.language', foreground: 'BFA4E8' },
      { token: 'entity.name.function', foreground: 'E4C87F' },
      { token: 'support.function', foreground: 'E4C87F' },
      { token: 'entity.name.type', foreground: '82B08D' },
      { token: 'variable', foreground: 'CDBFA2' },
      { token: 'variable.parameter', foreground: 'CDBFA2', fontStyle: 'italic' },
      { token: 'tag', foreground: 'BFA4E8' },
      { token: 'attribute.name', foreground: 'D4C3A1' },
      { token: 'attribute.value', foreground: 'D5A67A' },
      { token: 'namespace', foreground: '82B08D', fontStyle: 'italic' },
      { token: 'white', foreground: '242830' },
    ],
    colors: {
      'editor.background': '#090A0D',
      'editor.foreground': '#D8D6CF',
      'editor.lineHighlightBackground': '#15171D',
      'editor.lineHighlightBorder': '#00000000',
      'editor.selectionBackground': '#3C3327',
      'editor.inactiveSelectionBackground': '#2E2A24',
      'editor.selectionHighlightBackground': '#8A744333',
      'editor.wordHighlightBackground': '#4A4436B0',
      'editor.wordHighlightStrongBackground': '#6A5A3CB0',
      'editor.findMatchBackground': '#5F4D2F',
      'editor.findMatchHighlightBackground': '#8A744322',
      'editor.hoverHighlightBackground': '#4F463333',
      'editor.foldBackground': '#4F46331D',
      'editorBracketMatch.background': '#4A5E3A22',
      'editorBracketMatch.border': '#8B8B7A',
      'editorBracketHighlight.foreground1': '#E7CB7E',
      'editorBracketHighlight.foreground2': '#C79BE8',
      'editorBracketHighlight.foreground3': '#92B87A',
      'editorBracketHighlight.foreground4': '#E7CB7E',
      'editorBracketHighlight.foreground5': '#C79BE8',
      'editorBracketHighlight.foreground6': '#92B87A',
      'editorIndentGuide.background': '#282C34',
      'editorIndentGuide.activeBackground': '#4F534A',
      'editorCursor.foreground': '#CFCBBE',
      'editorLineNumber.foreground': '#62605A',
      'editorLineNumber.activeForeground': '#B2ADA2',
      'editorError.foreground': '#E26A6A',
      'editorWarning.foreground': '#D1AE62',
      'editorInfo.foreground': '#89B89B',
      'editorHint.foreground': '#DAD7CD',
      'editorGutter.background': '#090A0D',
      'editorGutter.modifiedBackground': '#A8834A',
      'editorGutter.addedBackground': '#5F8F63',
      'editorGutter.deletedBackground': '#C66B6B',
      'editorOverviewRuler.border': '#7F7F7F4D',
      'editorOverviewRuler.errorForeground': '#E26A6A',
      'editorOverviewRuler.warningForeground': '#D1AE62',
      'editorOverviewRuler.infoForeground': '#89B89B',
      'editorWidget.background': '#111318',
      'editorWidget.border': '#2B2E35',
      'editorSuggestWidget.background': '#111318',
      'editorSuggestWidget.border': '#2B2E35',
      'editorSuggestWidget.foreground': '#D8D6CF',
      'editorSuggestWidget.selectedBackground': '#39412F',
      'editorSuggestWidget.selectedForeground': '#FAF8F2',
      'editorSuggestWidget.highlightForeground': '#A8C56F',
      'editorHoverWidget.background': '#111318',
      'editorHoverWidget.border': '#2B2E35',
      'editorHoverWidget.foreground': '#D1CEC4',
      'editorCodeLens.foreground': '#8B887E',
      'editorInlayHint.background': '#3A3B3322',
      'editorInlayHint.foreground': '#A8A392',
      'editorWhitespace.foreground': '#242830',
      'editorRuler.foreground': '#353A33',
      'input.background': '#0E1014',
      'input.border': '#2B2E35',
      'input.foreground': '#D1CEC4',
      'input.placeholderForeground': '#888579',
      'scrollbar.shadow': '#000000',
      'scrollbarSlider.background': '#656A744A',
      'scrollbarSlider.hoverBackground': '#7379834F',
      'scrollbarSlider.activeBackground': '#838A9566',
      'minimap.background': '#090A0D',
      'diffEditor.insertedTextBackground': '#7D9A5022',
      'diffEditor.removedTextBackground': '#D46A6A22',
    },
  },
};
