import type { EditorColorScheme } from '../types/editorScheme';

export const vscodeLightPlus: EditorColorScheme = {
  id: 'vscode-light-plus',
  name: 'Light+ (VS Code)',
  type: 'light',
  monacoTheme: {
    base: 'vs',
    inherit: false,
    rules: [
      { token: '', foreground: '000000', background: 'FFFFFF' },
      // Comments
      { token: 'comment', foreground: '008000', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '008000', fontStyle: 'italic' },
      // Keywords
      { token: 'keyword', foreground: '0000FF' },
      { token: 'keyword.if', foreground: 'AF00DB' },
      { token: 'keyword.else', foreground: 'AF00DB' },
      { token: 'keyword.for', foreground: 'AF00DB' },
      { token: 'keyword.while', foreground: 'AF00DB' },
      { token: 'keyword.return', foreground: 'AF00DB' },
      { token: 'keyword.break', foreground: 'AF00DB' },
      { token: 'keyword.continue', foreground: 'AF00DB' },
      { token: 'keyword.switch', foreground: 'AF00DB' },
      { token: 'keyword.try', foreground: 'AF00DB' },
      { token: 'keyword.catch', foreground: 'AF00DB' },
      { token: 'keyword.throw', foreground: 'AF00DB' },
      { token: 'keyword.goto', foreground: 'AF00DB' },
      // Preprocessor
      { token: 'keyword.directive', foreground: 'AF00DB' },
      { token: 'keyword.directive.include', foreground: 'AF00DB' },
      { token: 'string.include.identifier', foreground: 'A31515' },
      // Identifiers
      { token: 'identifier', foreground: '001080' },
      // Strings
      { token: 'string', foreground: 'A31515' },
      { token: 'string.escape', foreground: 'EE0000' },
      { token: 'string.raw', foreground: 'A31515' },
      { token: 'string.invalid', foreground: 'CD3131' },
      { token: 'character', foreground: 'A31515' },
      // Numbers
      { token: 'number', foreground: '098658' },
      { token: 'number.float', foreground: '098658' },
      { token: 'number.hex', foreground: '098658' },
      { token: 'number.binary', foreground: '098658' },
      { token: 'number.octal', foreground: '098658' },
      // Delimiters
      { token: 'delimiter', foreground: '000000' },
      { token: 'delimiter.curly', foreground: '000000' },
      { token: 'delimiter.parenthesis', foreground: '000000' },
      { token: 'delimiter.angle', foreground: '000000' },
      { token: 'delimiter.square', foreground: '000000' },
      // Annotations
      { token: 'annotation', foreground: 'AF00DB' },
      // Regex
      { token: 'regexp', foreground: '811F3F' },
      // Invalid
      { token: 'invalid', foreground: 'CD3131', fontStyle: 'underline' },
      // TextMate fallbacks
      { token: 'type', foreground: '267F99' },
      { token: 'type.identifier', foreground: '267F99' },
      { token: 'keyword.control', foreground: 'AF00DB' },
      { token: 'storage', foreground: '0000FF' },
      { token: 'constant', foreground: '0070C1' },
      { token: 'entity.name.function', foreground: '795E26' },
      { token: 'support.function', foreground: '795E26' },
      { token: 'entity.name.type', foreground: '267F99' },
      { token: 'variable', foreground: '001080' },
      { token: 'variable.parameter', foreground: '001080', fontStyle: 'italic' },
      { token: 'tag', foreground: '800000' },
      { token: 'attribute.name', foreground: 'FF0000' },
      { token: 'attribute.value', foreground: '0000FF' },
      { token: 'namespace', foreground: '267F99', fontStyle: 'italic' },
      { token: 'white', foreground: 'D3D3D3' },
    ],
    colors: {
      'editor.background': '#FFFFFF',
      'editor.foreground': '#000000',
      'editor.lineHighlightBackground': '#F7F7F7',
      'editor.selectionBackground': '#ADD6FF',
      'editor.inactiveSelectionBackground': '#E5EBF1',
      'editor.selectionHighlightBackground': '#ADD6FF80',
      'editor.wordHighlightBackground': '#57575740',
      'editor.wordHighlightStrongBackground': '#0060C040',
      'editor.findMatchBackground': '#A8AC94',
      'editor.findMatchHighlightBackground': '#EA5C0040',
      'editorBracketMatch.background': '#0064001A',
      'editorBracketMatch.border': '#B9B9B9',
      'editorIndentGuide.background': '#D3D3D3',
      'editorIndentGuide.activeBackground': '#939393',
      'editorCursor.foreground': '#000000',
      'editorLineNumber.foreground': '#237893',
      'editorLineNumber.activeForeground': '#0B216F',
      'editorError.foreground': '#E51400',
      'editorWarning.foreground': '#BF8803',
      'editorInfo.foreground': '#1A85FF',
      'editorGutter.background': '#FFFFFF',
      'editorWidget.background': '#F3F3F3',
      'editorWidget.border': '#C8C8C8',
      'editorSuggestWidget.background': '#F3F3F3',
      'editorSuggestWidget.border': '#C8C8C8',
      'editorSuggestWidget.foreground': '#000000',
      'editorSuggestWidget.selectedBackground': '#0060C0',
      'editorSuggestWidget.selectedForeground': '#FFFFFF',
      'editorSuggestWidget.highlightForeground': '#0066BF',
      'editorHoverWidget.background': '#F3F3F3',
      'editorHoverWidget.border': '#C8C8C8',
      'editorHoverWidget.foreground': '#000000',
      'input.background': '#FFFFFF',
      'input.border': '#CECECE',
      'input.foreground': '#000000',
      'input.placeholderForeground': '#767676',
      'scrollbar.shadow': '#DDDDDD',
      'scrollbarSlider.background': '#64646466',
      'scrollbarSlider.hoverBackground': '#646464B3',
      'scrollbarSlider.activeBackground': '#00000099',
      'minimap.background': '#FFFFFF',
      'editorOverviewRuler.border': '#7F7F7F4D',
      'editorWhitespace.foreground': '#CCCCCC',
      'editorRuler.foreground': '#D3D3D3',
      'editorBracketHighlight.foreground1': '#0431FA',
      'editorBracketHighlight.foreground2': '#319331',
      'editorBracketHighlight.foreground3': '#7B3814',
      'editorBracketHighlight.foreground4': '#0431FA',
      'editorBracketHighlight.foreground5': '#319331',
      'editorBracketHighlight.foreground6': '#7B3814',
    },
  },
};
