import type { EditorColorScheme } from '../types/editorScheme';

export const vscodeDarkPlus: EditorColorScheme = {
  id: 'vscode-dark-plus',
  name: 'Dark+ (VS Code)',
  type: 'dark',
  monacoTheme: {
    base: 'vs-dark',
    inherit: false,
    rules: [
      // Default
      { token: '', foreground: 'D4D4D4', background: '1E1E1E' },
      // Comments
      { token: 'comment', foreground: '6A9955', fontStyle: 'italic' },
      { token: 'comment.doc', foreground: '6A9955', fontStyle: 'italic' },
      // Keywords (prefix-matches keyword.if, keyword.for, keyword.class, etc.)
      { token: 'keyword', foreground: '569CD6' },
      { token: 'keyword.if', foreground: 'C586C0' },
      { token: 'keyword.else', foreground: 'C586C0' },
      { token: 'keyword.for', foreground: 'C586C0' },
      { token: 'keyword.while', foreground: 'C586C0' },
      { token: 'keyword.do', foreground: 'C586C0' },
      { token: 'keyword.switch', foreground: 'C586C0' },
      { token: 'keyword.case', foreground: 'C586C0' },
      { token: 'keyword.return', foreground: 'C586C0' },
      { token: 'keyword.break', foreground: 'C586C0' },
      { token: 'keyword.continue', foreground: 'C586C0' },
      { token: 'keyword.try', foreground: 'C586C0' },
      { token: 'keyword.catch', foreground: 'C586C0' },
      { token: 'keyword.throw', foreground: 'C586C0' },
      { token: 'keyword.goto', foreground: 'C586C0' },
      // Preprocessor directives
      { token: 'keyword.directive', foreground: 'C586C0' },
      { token: 'keyword.directive.include', foreground: 'C586C0' },
      { token: 'string.include.identifier', foreground: 'CE9178' },
      // Identifiers (variables, functions, types, macros — all are identifier in Monaco C++)
      { token: 'identifier', foreground: '9CDCFE' },
      // Strings
      { token: 'string', foreground: 'CE9178' },
      { token: 'string.escape', foreground: 'D7BA7D' },
      { token: 'string.raw', foreground: 'CE9178' },
      { token: 'string.invalid', foreground: 'F44747' },
      { token: 'character', foreground: 'CE9178' },
      // Numbers
      { token: 'number', foreground: 'B5CEA8' },
      { token: 'number.float', foreground: 'B5CEA8' },
      { token: 'number.hex', foreground: 'B5CEA8' },
      { token: 'number.binary', foreground: 'B5CEA8' },
      { token: 'number.octal', foreground: 'B5CEA8' },
      // Operators & Delimiters
      { token: 'delimiter', foreground: 'D4D4D4' },
      { token: 'delimiter.curly', foreground: 'D4D4D4' },
      { token: 'delimiter.parenthesis', foreground: 'D4D4D4' },
      { token: 'delimiter.angle', foreground: 'D4D4D4' },
      { token: 'delimiter.square', foreground: 'D4D4D4' },
      // Annotations [[ ]]
      { token: 'annotation', foreground: 'C586C0' },
      // Regex (for JS/Python)
      { token: 'regexp', foreground: 'D16969' },
      // Invalid
      { token: 'invalid', foreground: 'F44747', fontStyle: 'underline' },
      // TextMate-style tokens (for non-C++ languages with richer tokenizers)
      { token: 'type', foreground: '4EC9B0' },
      { token: 'type.identifier', foreground: '4EC9B0' },
      { token: 'keyword.control', foreground: 'C586C0' },
      { token: 'storage', foreground: '569CD6' },
      { token: 'storage.type', foreground: '569CD6' },
      { token: 'constant', foreground: '4FC1FF' },
      { token: 'constant.language', foreground: '569CD6' },
      { token: 'entity.name.function', foreground: 'DCDCAA' },
      { token: 'support.function', foreground: 'DCDCAA' },
      { token: 'entity.name.type', foreground: '4EC9B0' },
      { token: 'variable', foreground: '9CDCFE' },
      { token: 'variable.parameter', foreground: '9CDCFE', fontStyle: 'italic' },
      { token: 'tag', foreground: '569CD6' },
      { token: 'attribute.name', foreground: '9CDCFE' },
      { token: 'attribute.value', foreground: 'CE9178' },
      { token: 'namespace', foreground: '4EC9B0', fontStyle: 'italic' },
      { token: 'white', foreground: '3B3B3B' },
    ],
    colors: {
      'editor.background': '#1E1E1E',
      'editor.foreground': '#D4D4D4',
      'editor.lineHighlightBackground': '#2A2D2E',
      'editor.lineHighlightBorder': '#2A2D2E00',
      'editor.selectionBackground': '#264F78',
      'editor.inactiveSelectionBackground': '#3A3D41',
      'editor.selectionHighlightBackground': '#ADD6FF26',
      'editor.wordHighlightBackground': '#575757B8',
      'editor.wordHighlightStrongBackground': '#004972B8',
      'editor.findMatchBackground': '#515C6A',
      'editor.findMatchHighlightBackground': '#EA5C0055',
      'editor.hoverHighlightBackground': '#264F7855',
      'editor.foldBackground': '#264F7822',
      'editorBracketMatch.background': '#0064001A',
      'editorBracketMatch.border': '#888888',
      'editorBracketHighlight.foreground1': '#FFD700',
      'editorBracketHighlight.foreground2': '#DA70D6',
      'editorBracketHighlight.foreground3': '#179FFF',
      'editorBracketHighlight.foreground4': '#FFD700',
      'editorBracketHighlight.foreground5': '#DA70D6',
      'editorBracketHighlight.foreground6': '#179FFF',
      'editorIndentGuide.background': '#404040',
      'editorIndentGuide.activeBackground': '#707070',
      'editorCursor.foreground': '#AEAFAD',
      'editorLineNumber.foreground': '#858585',
      'editorLineNumber.activeForeground': '#C6C6C6',
      'editorError.foreground': '#F48771',
      'editorWarning.foreground': '#CCA700',
      'editorInfo.foreground': '#75BEFF',
      'editorHint.foreground': '#EEEEEE',
      'editorGutter.background': '#1E1E1E',
      'editorGutter.modifiedBackground': '#1B81A8',
      'editorGutter.addedBackground': '#487E02',
      'editorGutter.deletedBackground': '#F14C4C',
      'editorOverviewRuler.border': '#7F7F7F4D',
      'editorOverviewRuler.errorForeground': '#F48771',
      'editorOverviewRuler.warningForeground': '#CCA700',
      'editorOverviewRuler.infoForeground': '#75BEFF',
      'editorWidget.background': '#252526',
      'editorWidget.border': '#454545',
      'editorSuggestWidget.background': '#252526',
      'editorSuggestWidget.border': '#454545',
      'editorSuggestWidget.foreground': '#D4D4D4',
      'editorSuggestWidget.selectedBackground': '#04395E',
      'editorSuggestWidget.selectedForeground': '#FFFFFF',
      'editorSuggestWidget.highlightForeground': '#18A3FF',
      'editorHoverWidget.background': '#252526',
      'editorHoverWidget.border': '#454545',
      'editorHoverWidget.foreground': '#CCCCCC',
      'editorCodeLens.foreground': '#999999',
      'editorInlayHint.background': '#4D4D4D55',
      'editorInlayHint.foreground': '#A0A0A0',
      'editorWhitespace.foreground': '#3B3B3B',
      'editorRuler.foreground': '#5A5A5A',
      'input.background': '#3C3C3C',
      'input.border': '#454545',
      'input.foreground': '#CCCCCC',
      'input.placeholderForeground': '#A6A6A6',
      'scrollbar.shadow': '#000000',
      'scrollbarSlider.background': '#79797966',
      'scrollbarSlider.hoverBackground': '#646464B3',
      'scrollbarSlider.activeBackground': '#BFBFBF66',
      'minimap.background': '#1E1E1E',
      'diffEditor.insertedTextBackground': '#9BB95522',
      'diffEditor.removedTextBackground': '#FF000033',
    },
  },
};
