import type { EditorColorScheme } from '../types/editorScheme';
import { vscodeDarkPlusPlus } from './vscodeDarkPlusPlus';

// Keep syntax colors identical to Night Dark Mode; only adjust non-syntax UI colors for Forge.
const forgeSyntaxRules = vscodeDarkPlusPlus.monacoTheme.rules.map((rule) => ({ ...rule }));
if (forgeSyntaxRules[0]?.token === '') {
  forgeSyntaxRules[0] = { ...forgeSyntaxRules[0], background: '070A08' };
}

export const vscodeDarkPlusPlusForge: EditorColorScheme = {
  id: 'vscode-dark-plus-plus-forge',
  name: 'Night Dark Forge',
  type: 'dark',
  monacoTheme: {
    base: 'vs-dark',
    inherit: false,
    rules: forgeSyntaxRules,
    colors: {
      'editor.background': '#070A08',
      'editor.foreground': '#D8D6CF',
      'editor.lineHighlightBackground': '#101611',
      'editor.lineHighlightBorder': '#00000000',
      'editor.selectionBackground': '#1F3A2F',
      'editor.inactiveSelectionBackground': '#162A21',
      'editor.selectionHighlightBackground': '#3A644D33',
      'editor.wordHighlightBackground': '#31503EB3',
      'editor.wordHighlightStrongBackground': '#46735AB3',
      'editor.findMatchBackground': '#35543F',
      'editor.findMatchHighlightBackground': '#5A8B6E24',
      'editor.hoverHighlightBackground': '#2B4A3933',
      'editor.foldBackground': '#2B4A391E',
      'editorBracketMatch.background': '#2D5A4326',
      'editorBracketMatch.border': '#6F9A80',
      'editorBracketHighlight.foreground1': '#E7CB7E',
      'editorBracketHighlight.foreground2': '#C79BE8',
      'editorBracketHighlight.foreground3': '#92B87A',
      'editorBracketHighlight.foreground4': '#E7CB7E',
      'editorBracketHighlight.foreground5': '#C79BE8',
      'editorBracketHighlight.foreground6': '#92B87A',
      'editorIndentGuide.background': '#223127',
      'editorIndentGuide.activeBackground': '#45624D',
      'editorCursor.foreground': '#CFCBBE',
      'editorLineNumber.foreground': '#5E7163',
      'editorLineNumber.activeForeground': '#AFC5B3',
      'editorError.foreground': '#E26A6A',
      'editorWarning.foreground': '#D1AE62',
      'editorInfo.foreground': '#89B89B',
      'editorHint.foreground': '#DAD7CD',
      'editorGutter.background': '#070A08',
      'editorGutter.modifiedBackground': '#3E7A5F',
      'editorGutter.addedBackground': '#5C9569',
      'editorGutter.deletedBackground': '#C66B6B',
      'editorOverviewRuler.border': '#7F7F7F4D',
      'editorOverviewRuler.errorForeground': '#E26A6A',
      'editorOverviewRuler.warningForeground': '#D1AE62',
      'editorOverviewRuler.infoForeground': '#89B89B',
      'editorWidget.background': '#0D1510',
      'editorWidget.border': '#234032',
      'editorSuggestWidget.background': '#0D1510',
      'editorSuggestWidget.border': '#234032',
      'editorSuggestWidget.foreground': '#D8D6CF',
      'editorSuggestWidget.selectedBackground': '#1E3E30',
      'editorSuggestWidget.selectedForeground': '#FAF8F2',
      'editorSuggestWidget.highlightForeground': '#A8C56F',
      'editorHoverWidget.background': '#0D1510',
      'editorHoverWidget.border': '#234032',
      'editorHoverWidget.foreground': '#D1CEC4',
      'editorCodeLens.foreground': '#8B887E',
      'editorInlayHint.background': '#29413322',
      'editorInlayHint.foreground': '#A8A392',
      'editorWhitespace.foreground': '#1E2620',
      'editorRuler.foreground': '#2D3F34',
      'input.background': '#0B120E',
      'input.border': '#234032',
      'input.foreground': '#D1CEC4',
      'input.placeholderForeground': '#77907E',
      'scrollbar.shadow': '#000000',
      'scrollbarSlider.background': '#5D7A664A',
      'scrollbarSlider.hoverBackground': '#6C8D774F',
      'scrollbarSlider.activeBackground': '#7FA38966',
      'minimap.background': '#070A08',
      'diffEditor.insertedTextBackground': '#6EA97E22',
      'diffEditor.removedTextBackground': '#D7737322',
    },
  },
};
