import type { AIProvider, ModelDefinition, ProviderConfig } from '../types/ai';

export const OPENROUTER_CONFIG: ProviderConfig = {
  id: 'openrouter',
  name: 'OpenRouter',
  displayName: 'OpenRouter',
  icon: 'OR',
  baseUrl: 'https://openrouter.ai/api/v1',
  authType: 'bearer',
  supportsStreaming: true,
  supportsFIM: false,
  customModelAllowed: true,
  requiresApiKey: true,
  models: [
    {
      id: 'anthropic/claude-3.5-sonnet',
      name: 'claude-3.5-sonnet',
      displayName: 'Claude 3.5 Sonnet',
      contextWindow: 200000,
      maxOutputTokens: 8192,
      costPer1kInput: 0.003,
      costPer1kOutput: 0.015,
      recommended: true,
      capabilities: ['code-completion', 'chat', 'reasoning'],
      description: 'Strong code model with large context.',
    },
    {
      id: 'openai/gpt-4o',
      name: 'gpt-4o',
      displayName: 'GPT-4o',
      contextWindow: 128000,
      maxOutputTokens: 4096,
      costPer1kInput: 0.005,
      costPer1kOutput: 0.015,
      recommended: true,
      capabilities: ['code-completion', 'chat', 'function-calling', 'vision'],
      description: 'Fast multimodal model with strong coding performance.',
    },
    {
      id: 'openai/gpt-4o-mini',
      name: 'gpt-4o-mini',
      displayName: 'GPT-4o Mini',
      contextWindow: 128000,
      maxOutputTokens: 16384,
      costPer1kInput: 0.00015,
      costPer1kOutput: 0.0006,
      capabilities: ['code-completion', 'chat'],
      description: 'Low-cost option for frequent completions.',
    },
    {
      id: 'mistralai/codestral-latest',
      name: 'codestral',
      displayName: 'Codestral',
      contextWindow: 32000,
      maxOutputTokens: 4096,
      costPer1kInput: 0.001,
      costPer1kOutput: 0.003,
      recommended: true,
      capabilities: ['code-completion', 'fim'],
      description: 'Code-specialized model available through OpenRouter.',
    },
    {
      id: 'meta-llama/llama-3.1-70b-instruct',
      name: 'llama-3.1-70b',
      displayName: 'Llama 3.1 70B',
      contextWindow: 131072,
      maxOutputTokens: 4096,
      costPer1kInput: 0.0004,
      costPer1kOutput: 0.0004,
      capabilities: ['code-completion', 'chat'],
      description: 'Balanced quality and price.',
    },
    {
      id: 'qwen/qwen-2.5-coder-32b-instruct',
      name: 'qwen-2.5-coder',
      displayName: 'Qwen 2.5 Coder 32B',
      contextWindow: 32768,
      maxOutputTokens: 4096,
      costPer1kInput: 0.0002,
      costPer1kOutput: 0.0002,
      recommended: true,
      capabilities: ['code-completion', 'chat'],
      description: 'Strong code understanding at low cost.',
    },
  ],
};

export const DEEPSEEK_CONFIG: ProviderConfig = {
  id: 'deepseek',
  name: 'DeepSeek',
  displayName: 'DeepSeek',
  icon: 'DS',
  baseUrl: 'https://api.deepseek.com',
  authType: 'bearer',
  supportsStreaming: true,
  supportsFIM: true,
  customModelAllowed: false,
  requiresApiKey: true,
  models: [
    {
      id: 'deepseek-coder',
      name: 'deepseek-coder',
      displayName: 'DeepSeek Coder',
      contextWindow: 128000,
      maxOutputTokens: 4096,
      costPer1kInput: 0.00014,
      costPer1kOutput: 0.00028,
      recommended: true,
      capabilities: ['code-completion', 'fim', 'chat'],
      description: 'Code-focused model with FIM support.',
    },
    {
      id: 'deepseek-chat',
      name: 'deepseek-chat',
      displayName: 'DeepSeek Chat',
      contextWindow: 128000,
      maxOutputTokens: 4096,
      costPer1kInput: 0.00014,
      costPer1kOutput: 0.00028,
      capabilities: ['code-completion', 'chat', 'fim'],
      description: 'General DeepSeek model that also works well for code.',
    },
    {
      id: 'deepseek-reasoner',
      name: 'deepseek-reasoner',
      displayName: 'DeepSeek Reasoner',
      contextWindow: 64000,
      maxOutputTokens: 8192,
      costPer1kInput: 0.00055,
      costPer1kOutput: 0.00219,
      capabilities: ['code-completion', 'chat', 'reasoning'],
      description: 'Best when reasoning quality matters more than speed.',
    },
  ],
};

export const GOOGLE_AI_CONFIG: ProviderConfig = {
  id: 'google',
  name: 'Google AI Studio',
  displayName: 'Google AI',
  icon: 'GA',
  baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
  authType: 'api-key',
  supportsStreaming: true,
  supportsFIM: false,
  customModelAllowed: true,
  requiresApiKey: true,
  models: [
    {
      id: 'gemini-3-flash-preview',
      name: 'gemini-3-flash-preview',
      displayName: 'Gemini 3 Flash Preview',
      contextWindow: 1048576,
      maxOutputTokens: 8192,
      costPer1kInput: 0,
      costPer1kOutput: 0,
      recommended: true,
      capabilities: ['code-completion', 'chat', 'vision', 'reasoning'],
      description: 'Preview Gemini Flash model for fast coding and reasoning.',
    },
    {
      id: 'gemini-flash-latest',
      name: 'gemini-flash-latest',
      displayName: 'Gemini Flash (Latest)',
      contextWindow: 1048576,
      maxOutputTokens: 8192,
      costPer1kInput: 0,
      costPer1kOutput: 0,
      recommended: true,
      capabilities: ['code-completion', 'chat', 'vision'],
      description: 'Rolling latest Gemini Flash alias.',
    },
    {
      id: 'gemini-2.0-flash',
      name: 'gemini-2.0-flash',
      displayName: 'Gemini 2.0 Flash',
      contextWindow: 1048576,
      maxOutputTokens: 8192,
      costPer1kInput: 0,
      costPer1kOutput: 0,
      recommended: true,
      capabilities: ['code-completion', 'chat', 'vision'],
      description: 'Fast Gemini model with a large context window.',
    },
    {
      id: 'gemini-2.0-flash-thinking',
      name: 'gemini-2.0-flash-thinking',
      displayName: 'Gemini 2.0 Flash Thinking',
      contextWindow: 1048576,
      maxOutputTokens: 8192,
      costPer1kInput: 0,
      costPer1kOutput: 0,
      capabilities: ['code-completion', 'chat', 'reasoning'],
      description: 'Reasoning-flavored Gemini variant.',
    },
    {
      id: 'gemini-1.5-pro',
      name: 'gemini-1.5-pro',
      displayName: 'Gemini 1.5 Pro',
      contextWindow: 2000000,
      maxOutputTokens: 8192,
      costPer1kInput: 0.00125,
      costPer1kOutput: 0.005,
      capabilities: ['code-completion', 'chat', 'vision'],
      description: 'Very large context window for broad project context.',
    },
    {
      id: 'gemini-1.5-flash',
      name: 'gemini-1.5-flash',
      displayName: 'Gemini 1.5 Flash',
      contextWindow: 1000000,
      maxOutputTokens: 8192,
      costPer1kInput: 0.000075,
      costPer1kOutput: 0.0003,
      recommended: true,
      capabilities: ['code-completion', 'chat', 'vision'],
      description: 'Fast and inexpensive Gemini tier.',
    },
    {
      id: 'gemini-pro',
      name: 'gemini-pro',
      displayName: 'Gemini Pro',
      contextWindow: 32760,
      maxOutputTokens: 8192,
      costPer1kInput: 0.0005,
      costPer1kOutput: 0.0015,
      capabilities: ['code-completion', 'chat'],
    },
  ],
};

export const HUGGING_FACE_CONFIG: ProviderConfig = {
  id: 'huggingface',
  name: 'Hugging Face',
  displayName: 'Hugging Face',
  icon: 'HF',
  baseUrl: 'https://router.huggingface.co/v1',
  authType: 'bearer',
  supportsStreaming: true,
  supportsFIM: false,
  customModelAllowed: true,
  requiresApiKey: true,
  models: [
    {
      id: 'Qwen/Qwen2.5-Coder-32B-Instruct',
      name: 'qwen2.5-coder-32b',
      displayName: 'Qwen 2.5 Coder 32B',
      contextWindow: 32768,
      maxOutputTokens: 4096,
      recommended: true,
      capabilities: ['code-completion', 'chat'],
      description: 'Strong coding model available through Hugging Face Inference.',
    },
    {
      id: 'deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct',
      name: 'deepseek-coder-v2-lite',
      displayName: 'DeepSeek Coder V2 Lite',
      contextWindow: 32768,
      maxOutputTokens: 4096,
      capabilities: ['code-completion', 'chat'],
      description: 'Efficient coding model with good completion quality.',
    },
    {
      id: 'mistralai/Mistral-Nemo-Instruct-2407',
      name: 'mistral-nemo-instruct',
      displayName: 'Mistral Nemo Instruct',
      contextWindow: 128000,
      maxOutputTokens: 4096,
      capabilities: ['code-completion', 'chat', 'reasoning'],
      description: 'Balanced model for code generation and reasoning tasks.',
    },
    {
      id: 'meta-llama/Llama-3.3-70B-Instruct',
      name: 'llama-3.3-70b-instruct',
      displayName: 'Llama 3.3 70B Instruct',
      contextWindow: 131072,
      maxOutputTokens: 4096,
      capabilities: ['code-completion', 'chat'],
      description: 'General-purpose large model for robust coding support.',
    },
  ],
};

export const OLLAMA_CONFIG: ProviderConfig = {
  id: 'ollama',
  name: 'Ollama',
  displayName: 'Ollama (Local)',
  icon: 'OL',
  baseUrl: 'http://localhost:11434',
  authType: 'none',
  supportsStreaming: true,
  supportsFIM: true,
  customModelAllowed: true,
  requiresApiKey: false,
  models: [
    {
      id: 'deepseek-coder-v2:latest',
      name: 'deepseek-coder-v2',
      displayName: 'DeepSeek Coder V2',
      contextWindow: 128000,
      maxOutputTokens: 4096,
      recommended: true,
      capabilities: ['code-completion', 'fim', 'chat'],
      description: 'A strong local code-completion default.',
    },
    {
      id: 'qwen2.5-coder:latest',
      name: 'qwen2.5-coder',
      displayName: 'Qwen 2.5 Coder',
      contextWindow: 32768,
      maxOutputTokens: 4096,
      recommended: true,
      capabilities: ['code-completion', 'chat'],
    },
    {
      id: 'codellama:latest',
      name: 'codellama',
      displayName: 'Code Llama',
      contextWindow: 16384,
      maxOutputTokens: 4096,
      capabilities: ['code-completion', 'fim'],
    },
    {
      id: 'starcoder2:latest',
      name: 'starcoder2',
      displayName: 'StarCoder 2',
      contextWindow: 16384,
      maxOutputTokens: 4096,
      capabilities: ['code-completion', 'fim'],
    },
  ],
};

export const CUSTOM_PROVIDER_CONFIG: ProviderConfig = {
  id: 'custom',
  name: 'Custom',
  displayName: 'Custom Endpoint',
  icon: 'CU',
  baseUrl: '',
  authType: 'bearer',
  supportsStreaming: true,
  supportsFIM: false,
  customModelAllowed: true,
  requiresApiKey: true,
  models: [],
};

export const AI_PROVIDERS: Record<AIProvider, ProviderConfig> = {
  openrouter: OPENROUTER_CONFIG,
  deepseek: DEEPSEEK_CONFIG,
  google: GOOGLE_AI_CONFIG,
  huggingface: HUGGING_FACE_CONFIG,
  ollama: OLLAMA_CONFIG,
  custom: CUSTOM_PROVIDER_CONFIG,
};

export const POPULAR_OPENROUTER_MODELS = [
  'anthropic/claude-3.5-sonnet',
  'openai/gpt-4o',
  'mistralai/codestral-latest',
  'qwen/qwen-2.5-coder-32b-instruct',
  'meta-llama/llama-3.1-70b-instruct',
];

export const DEFAULT_PROVIDER: AIProvider = 'deepseek';
export const DEFAULT_MODEL = 'deepseek-coder';

export function findModelDefinition(provider: AIProvider, modelId: string): ModelDefinition | undefined {
  return AI_PROVIDERS[provider].models.find((candidate) => candidate.id === modelId);
}

