import type { Keybinding } from '../types';

export const defaultKeybindings: Keybinding[] = [
  // FILE
  { id: 'kb-file-new', key: 'ctrl+n', command: 'file.newFile', label: 'New File' },
  { id: 'kb-file-newcp', key: 'ctrl+alt+n', command: 'file.newCPFile', label: 'New CP File' },
  { id: 'kb-file-newwindow', key: 'ctrl+shift+n', command: 'file.newWindow', label: 'New Window' },
  { id: 'kb-file-open', key: 'ctrl+o', command: 'file.openFile', label: 'Open File' },
  { id: 'kb-file-openfolder', key: 'ctrl+k ctrl+o', command: 'file.openFolder', label: 'Open Folder' },
  { id: 'kb-file-save', key: 'ctrl+s', command: 'file.save', label: 'Save' },
  { id: 'kb-file-saveas', key: 'ctrl+shift+s', command: 'file.saveAs', label: 'Save As' },
  { id: 'kb-file-saveall', key: 'ctrl+alt+s', command: 'file.saveAll', label: 'Save All' },
  { id: 'kb-file-close', key: 'ctrl+w', command: 'file.closeTab', label: 'Close Tab' },
  { id: 'kb-file-closewindow', key: 'ctrl+shift+w', command: 'file.closeWindow', label: 'Close Window' },
  { id: 'kb-file-reopen', key: 'ctrl+shift+t', command: 'file.reopenClosedTab', label: 'Reopen Closed Tab' },
  { id: 'kb-file-nexttab', key: 'ctrl+tab', command: 'file.nextTab', label: 'Next Tab' },
  { id: 'kb-file-prevtab', key: 'ctrl+shift+tab', command: 'file.previousTab', label: 'Previous Tab' },
  { id: 'kb-file-tab1', key: 'alt+1', command: 'file.goToTab1', label: 'Go to Tab 1' },
  { id: 'kb-file-tab2', key: 'alt+2', command: 'file.goToTab2', label: 'Go to Tab 2' },
  { id: 'kb-file-tab3', key: 'alt+3', command: 'file.goToTab3', label: 'Go to Tab 3' },
  { id: 'kb-file-tab4', key: 'alt+4', command: 'file.goToTab4', label: 'Go to Tab 4' },
  { id: 'kb-file-tab5', key: 'alt+5', command: 'file.goToTab5', label: 'Go to Tab 5' },
  { id: 'kb-file-tab6', key: 'alt+6', command: 'file.goToTab6', label: 'Go to Tab 6' },
  { id: 'kb-file-tab7', key: 'alt+7', command: 'file.goToTab7', label: 'Go to Tab 7' },
  { id: 'kb-file-tab8', key: 'alt+8', command: 'file.goToTab8', label: 'Go to Tab 8' },
  { id: 'kb-file-tab9', key: 'alt+9', command: 'file.goToTab9', label: 'Go to Tab 9' },

  // EDIT
  { id: 'kb-edit-deleteline', key: 'ctrl+shift+k', command: 'edit.deleteLine', label: 'Delete Line' },
  { id: 'kb-edit-dupline', key: 'ctrl+shift+d', command: 'edit.duplicateLine', label: 'Duplicate Line' },
  { id: 'kb-edit-moveup', key: 'ctrl+shift+up', command: 'edit.moveLineUp', label: 'Move Line Up' },
  { id: 'kb-edit-movedown', key: 'ctrl+shift+down', command: 'edit.moveLineDown', label: 'Move Line Down' },
  { id: 'kb-edit-insertafter', key: 'ctrl+enter', command: 'edit.insertLineAfter', label: 'Insert Line After' },
  { id: 'kb-edit-insertbefore', key: 'ctrl+shift+enter', command: 'edit.insertLineBefore', label: 'Insert Line Before' },
  { id: 'kb-edit-joinlines', key: 'ctrl+j', command: 'edit.joinLines', label: 'Join Lines' },
  { id: 'kb-edit-comment', key: 'ctrl+/', command: 'edit.toggleComment', label: 'Toggle Comment' },
  { id: 'kb-edit-blockcomment', key: 'ctrl+shift+/', command: 'edit.toggleBlockComment', label: 'Toggle Block Comment' },
  { id: 'kb-edit-indent', key: 'ctrl+]', command: 'edit.indentLine', label: 'Indent Line' },
  { id: 'kb-edit-outdent', key: 'ctrl+[', command: 'edit.outdentLine', label: 'Outdent Line' },
  { id: 'kb-edit-upper', key: 'ctrl+k ctrl+u', command: 'edit.upperCase', label: 'Upper Case' },
  { id: 'kb-edit-lower', key: 'ctrl+k ctrl+l', command: 'edit.lowerCase', label: 'Lower Case' },

  // SELECTION
  { id: 'kb-sel-addnext', key: 'ctrl+d', command: 'selection.addNextOccurrence', label: 'Add Next Occurrence' },
  { id: 'kb-sel-alloccur', key: 'alt+f3', command: 'selection.selectAllOccurrences', label: 'Select All Occurrences' },
  { id: 'kb-sel-skip', key: 'ctrl+k ctrl+d', command: 'selection.skipOccurrence', label: 'Skip Occurrence' },
  { id: 'kb-sel-line', key: 'ctrl+l', command: 'selection.selectLine', label: 'Select Line' },
  { id: 'kb-sel-splitlines', key: 'ctrl+shift+l', command: 'selection.splitIntoLines', label: 'Split Into Lines' },
  { id: 'kb-sel-brackets', key: 'ctrl+shift+m', command: 'selection.expandToBrackets', label: 'Expand to Brackets' },
  { id: 'kb-sel-cursorup', key: 'ctrl+alt+up', command: 'selection.addCursorAbove', label: 'Add Cursor Above' },
  { id: 'kb-sel-cursordown', key: 'ctrl+alt+down', command: 'selection.addCursorBelow', label: 'Add Cursor Below' },
  { id: 'kb-sel-escape', key: 'escape', command: 'selection.singleCursor', label: 'Single Cursor', when: 'editorFocus' },

  // NAVIGATION
  { id: 'kb-nav-quickopen', key: 'ctrl+p', command: 'navigation.quickOpen', label: 'Quick Open' },
  { id: 'kb-nav-gotoline', key: 'ctrl+g', command: 'navigation.goToLine', label: 'Go to Line' },
  { id: 'kb-nav-gotosymbol', key: 'ctrl+r', command: 'navigation.goToSymbol', label: 'Go to Symbol' },
  { id: 'kb-nav-cmdpalette', key: 'ctrl+shift+p', command: 'navigation.commandPalette', label: 'Command Palette' },
  { id: 'kb-nav-matchbracket', key: 'ctrl+m', command: 'navigation.goToMatchingBracket', label: 'Go to Matching Bracket' },
  { id: 'kb-nav-back', key: 'alt+left', command: 'navigation.goBack', label: 'Go Back' },
  { id: 'kb-nav-forward', key: 'alt+right', command: 'navigation.goForward', label: 'Go Forward' },
  { id: 'kb-nav-bookmark', key: 'ctrl+f2', command: 'navigation.toggleBookmark', label: 'Toggle Bookmark' },
  { id: 'kb-nav-nextbookmark', key: 'f2', command: 'navigation.nextBookmark', label: 'Next Bookmark' },
  { id: 'kb-nav-prevbookmark', key: 'shift+f2', command: 'navigation.previousBookmark', label: 'Previous Bookmark' },

  // SEARCH
  { id: 'kb-search-find', key: 'ctrl+f', command: 'search.find', label: 'Find' },
  { id: 'kb-search-replace', key: 'ctrl+h', command: 'search.findReplace', label: 'Find and Replace' },
  { id: 'kb-search-infiles', key: 'ctrl+shift+f', command: 'search.findInFiles', label: 'Find in Files' },
  { id: 'kb-search-next', key: 'f3', command: 'search.findNext', label: 'Find Next' },
  { id: 'kb-search-prev', key: 'shift+f3', command: 'search.findPrevious', label: 'Find Previous' },
  { id: 'kb-search-word', key: 'ctrl+f3', command: 'search.findWordUnderCursor', label: 'Find Word Under Cursor' },
  { id: 'kb-search-replall', key: 'ctrl+alt+enter', command: 'search.replaceAll', label: 'Replace All' },

  // VIEW
  { id: 'kb-view-sidebar', key: 'ctrl+k ctrl+b', command: 'view.toggleSidebar', label: 'Toggle Sidebar' },
  { id: 'kb-view-terminal', key: 'ctrl+`', command: 'view.toggleTerminal', label: 'Toggle Terminal' },
  { id: 'kb-view-newterm', key: 'ctrl+shift+`', command: 'view.newTerminal', label: 'New Terminal' },
  { id: 'kb-view-fullscreen', key: 'f11', command: 'view.toggleFullscreen', label: 'Toggle Fullscreen' },
  { id: 'kb-view-zen', key: 'shift+f11', command: 'view.toggleZenMode', label: 'Toggle Zen Mode' },
  { id: 'kb-view-zoomin', key: 'ctrl+=', command: 'view.zoomIn', label: 'Zoom In' },
  { id: 'kb-view-zoomout', key: 'ctrl+-', command: 'view.zoomOut', label: 'Zoom Out' },
  { id: 'kb-view-zoomreset', key: 'ctrl+0', command: 'view.zoomReset', label: 'Zoom Reset' },
  { id: 'kb-view-single', key: 'alt+shift+1', command: 'view.layoutSingle', label: 'Single Layout' },
  { id: 'kb-view-2col', key: 'alt+shift+2', command: 'view.layoutTwoColumns', label: 'Two Columns' },
  { id: 'kb-view-3col', key: 'alt+shift+3', command: 'view.layoutThreeColumns', label: 'Three Columns' },
  { id: 'kb-view-grid', key: 'alt+shift+5', command: 'view.layoutGrid', label: 'Grid Layout' },
  { id: 'kb-view-2row', key: 'alt+shift+8', command: 'view.layoutTwoRows', label: 'Two Rows' },
  { id: 'kb-view-focus1', key: 'ctrl+1', command: 'view.focusGroup1', label: 'Focus Group 1' },
  { id: 'kb-view-focus2', key: 'ctrl+2', command: 'view.focusGroup2', label: 'Focus Group 2' },
  { id: 'kb-view-focus3', key: 'ctrl+3', command: 'view.focusGroup3', label: 'Focus Group 3' },
  { id: 'kb-view-focus4', key: 'ctrl+4', command: 'view.focusGroup4', label: 'Focus Group 4' },

  // FOLD
  { id: 'kb-fold-region', key: 'ctrl+shift+[', command: 'fold.foldRegion', label: 'Fold Region' },
  { id: 'kb-unfold-region', key: 'ctrl+shift+]', command: 'fold.unfoldRegion', label: 'Unfold Region' },
  { id: 'kb-fold-all', key: 'ctrl+k ctrl+0', command: 'fold.foldAll', label: 'Fold All' },
  { id: 'kb-unfold-all', key: 'ctrl+k ctrl+j', command: 'fold.unfoldAll', label: 'Unfold All' },
  { id: 'kb-fold-1', key: 'ctrl+k ctrl+1', command: 'fold.foldLevel1', label: 'Fold Level 1' },
  { id: 'kb-fold-2', key: 'ctrl+k ctrl+2', command: 'fold.foldLevel2', label: 'Fold Level 2' },
  { id: 'kb-fold-3', key: 'ctrl+k ctrl+3', command: 'fold.foldLevel3', label: 'Fold Level 3' },
  { id: 'kb-fold-4', key: 'ctrl+k ctrl+4', command: 'fold.foldLevel4', label: 'Fold Level 4' },
  { id: 'kb-fold-5', key: 'ctrl+k ctrl+5', command: 'fold.foldLevel5', label: 'Fold Level 5' },

  // BUILD
  { id: 'kb-build-run', key: 'ctrl+b', command: 'build.compileAndRun', label: 'Compile & Run' },
  { id: 'kb-build-compile', key: 'ctrl+shift+b', command: 'build.compileOnly', label: 'Compile Only' },
  { id: 'kb-build-runonly', key: 'ctrl+f5', command: 'build.runOnly', label: 'Run Only' },
  { id: 'kb-build-kill', key: 'ctrl+k', command: 'build.killProcess', label: 'Kill Process' },
  { id: 'kb-build-testall', key: 'ctrl+alt+t', command: 'build.runAllTestCases', label: 'Run All Test Cases' },
  { id: 'kb-build-tc1', key: 'ctrl+alt+1', command: 'build.runTestCase1', label: 'Run Test Case 1' },
  { id: 'kb-build-tc2', key: 'ctrl+alt+2', command: 'build.runTestCase2', label: 'Run Test Case 2' },
  { id: 'kb-build-tc3', key: 'ctrl+alt+3', command: 'build.runTestCase3', label: 'Run Test Case 3' },

  // SETTINGS
  { id: 'kb-settings-open', key: 'ctrl+,', command: 'settings.openSettings', label: 'Open Settings' },
];
