import type { AppSettings } from '../types';

export const defaultSettings: AppSettings = {
  editor: {
    fontFamily: '"Consolas", "Courier New", monospace',
    fontSize: 15,
    lineHeight: 1.7,
    tabSize: 4,
    insertSpaces: true,
    wordWrap: 'off',
    wordWrapColumn: 120,
    minimap: false,
    lineNumbers: 'on',
    cursorStyle: 'line',
    cursorBlinking: 'smooth',
    cursorWidth: 2,
    smoothScrolling: true,
    fontLigatures: true,
    fontWeight: 'normal',
    fontStyle: 'normal',
    renderWhitespace: 'none',
    bracketPairColorization: true,
    autoClosingBrackets: 'always',
    autoClosingQuotes: 'always',
    formatOnPaste: false,
    formatOnType: false,
    snippetSuggestions: 'top',
    suggestOnTriggerCharacters: true,
    acceptSuggestionOnEnter: 'on',
    mouseWheelZoom: false,
    stickyScroll: false,
    linkedEditing: false,
    guides: {
      indentation: true,
      bracketPairs: true,
    },
  },
  ui: {
    theme: 'vscode-dark',
    editorColorScheme: 'vscode-dark-plus',
    sidebarWidth: 260,
    sidebarVisible: true,
    bottomPanelHeight: 250,
    bottomPanelVisible: false,
    statusBarVisible: true,
    menuBarVisible: true,
    activityBarVisible: true,
    zoomLevel: 100,
    fontFamily: '"Segoe UI", sans-serif',
    fontSize: 13,
  },
  build: {
    compilerPath: 'g++',
    defaultProfile: 'Competitive',
    saveBeforeBuild: true,
    clearOutputBeforeBuild: true,
    showExecutionTime: true,
  },
  template: {
    autoInsert: true,
    showAnimation: true,
  },
  terminal: {
    fontFamily: '"JetBrains Mono", "Cascadia Mono", "Consolas", monospace',
    fontSize: 14,
    lineHeight: 1.4,
    cursorStyle: 'block',
    cursorBlink: true,
    scrollback: 5000,
  },
  files: {
    autoSave: 'off',
    autoSaveDelay: 1000,
    trimTrailingWhitespace: false,
    insertFinalNewline: false,
    encoding: 'utf-8',
    eol: 'auto',
    hotExit: true,
    exclude: ['.git', 'node_modules', 'target', '__pycache__', '*.exe', '*.o', '*.obj'],
  },
  animations: {
    enabled: true,
    duration: 150,
  },
};
