import type { ThemeDefinition } from '../types';

export const dawnTheme: ThemeDefinition = {
  id: 'dawn',
  name: 'Doom Code Dawn',
  type: 'light',
  colors: {
    bgDeepest: '#fdf6e3',
    bgBase: '#faf3e0',
    bgSurface: '#f5edd6',
    bgElevated: '#efe7cc',
    bgOverlay: '#e8dfc2',
    bgHighlight: '#ddd5b4',
    bgActive: '#d3caa5',
    bgIntense: '#c8bf96',
    accentPrimary: '#b57614',
    accentSecondary: '#a66a12',
    accentTertiary: '#975e10',
    accentGlow: '#d49a4e',
    accentBlue: '#268bd2',
    accentGreen: '#859900',
    accentRed: '#dc322f',
    accentYellow: '#b58900',
    accentOrange: '#cb4b16',
    accentPurple: '#6c71c4',
    accentCyan: '#2aa198',
    accentTeal: '#2aa198',
    accentPink: '#d33682',
    textPrimary: '#073642',
    textSecondary: '#586e75',
    textMuted: '#93a1a1',
    textFaint: '#c0c8c8',
    textInverse: '#fdf6e3',
    borderSubtle: '#e8dfc2',
    borderDefault: '#ddd5b4',
    borderStrong: '#c8bf96',
    borderAccent: '#b57614',
    scrollbarThumb: '#c8bf96',
    scrollbarThumbHover: '#b5ad87',
    scrollbarTrack: 'transparent',
  },
  monacoTheme: {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '93a1a1', fontStyle: 'italic' },
      { token: 'keyword', foreground: '6c71c4', fontStyle: 'bold' },
      { token: 'keyword.control', foreground: '6c71c4', fontStyle: 'bold' },
      { token: 'storage.type', foreground: '268bd2' },
      { token: 'type', foreground: '2aa198' },
      { token: 'entity.name.function', foreground: '268bd2', fontStyle: 'bold' },
      { token: 'variable', foreground: '073642' },
      { token: 'variable.parameter', foreground: 'b58900', fontStyle: 'italic' },
      { token: 'constant', foreground: 'cb4b16' },
      { token: 'number', foreground: 'cb4b16' },
      { token: 'string', foreground: '859900' },
      { token: 'string.escape', foreground: '2aa198', fontStyle: 'bold' },
      { token: 'preprocessor', foreground: 'b58900' },
      { token: 'operator', foreground: '2aa198' },
      { token: 'delimiter', foreground: '586e75' },
      { token: 'namespace', foreground: '2aa198', fontStyle: 'italic' },
      { token: 'identifier', foreground: '073642' },
      { token: '', foreground: '073642' },
    ],
    colors: {
      'editor.background': '#faf3e0',
      'editor.foreground': '#073642',
      'editor.lineHighlightBackground': '#efe7cc',
      'editor.selectionBackground': '#d3caa580',
      'editor.selectionHighlightBackground': '#d3caa540',
      'editorCursor.foreground': '#b57614',
      'editorLineNumber.foreground': '#c0c8c8',
      'editorLineNumber.activeForeground': '#b57614',
      'editorBracketMatch.background': '#b5761420',
      'editorBracketMatch.border': '#b57614',
      'editorIndentGuide.background': '#e8dfc2',
      'editorIndentGuide.activeBackground': '#c8bf96',
      'editorWidget.background': '#e8dfc2',
      'editorWidget.border': '#ddd5b4',
      'input.background': '#f5edd6',
      'input.border': '#ddd5b4',
      'input.foreground': '#073642',
    },
  },
};
