import type { ThemeDefinition } from '../types';

export const obsidianTheme: ThemeDefinition = {
  id: 'obsidian',
  name: 'Doom Code Claude',
  type: 'dark',
  colors: {
    bgDeepest: '#171714',
    bgBase: '#1d1d1a',
    bgSurface: '#252420',
    bgElevated: '#2e2d28',
    bgOverlay: '#1d1d1ae6',
    bgHighlight: '#35342e',
    bgActive: '#3e3d36',
    bgIntense: '#48473f',
    accentPrimary: '#da7756',
    accentSecondary: '#c96442',
    accentTertiary: '#b8573a',
    accentGlow: '#e8956f',
    accentBlue: '#6b9fdb',
    accentGreen: '#7ec77e',
    accentRed: '#e5655b',
    accentYellow: '#d4a94e',
    accentOrange: '#e8956f',
    accentPurple: '#a48bcb',
    accentCyan: '#5fb3c4',
    accentTeal: '#5cb8a5',
    accentPink: '#d4789c',
    textPrimary: '#e8e4df',
    textSecondary: '#b5b0a8',
    textMuted: '#7a766e',
    textFaint: '#4a4740',
    textInverse: '#1d1d1a',
    borderSubtle: '#2a2925',
    borderDefault: '#35342e',
    borderStrong: '#45443d',
    borderAccent: '#da7756',
    scrollbarThumb: '#35342e',
    scrollbarThumbHover: '#45443d',
    scrollbarTrack: 'transparent',
  },
  monacoTheme: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '565f89', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'bb9af7', fontStyle: 'bold' },
      { token: 'keyword.control', foreground: 'bb9af7', fontStyle: 'bold' },
      { token: 'storage.type', foreground: '7aa2f7' },
      { token: 'storage.modifier', foreground: '7aa2f7', fontStyle: 'italic' },
      { token: 'type', foreground: '7dcfff' },
      { token: 'type.identifier', foreground: '7dcfff' },
      { token: 'entity.name.function', foreground: '7aa2f7', fontStyle: 'bold' },
      { token: 'entity.name.type', foreground: '7dcfff' },
      { token: 'variable', foreground: 'c0caf5' },
      { token: 'variable.parameter', foreground: 'e0af68', fontStyle: 'italic' },
      { token: 'constant', foreground: 'ff9e64' },
      { token: 'constant.numeric', foreground: 'ff9e64' },
      { token: 'constant.language', foreground: 'ff9e64' },
      { token: 'number', foreground: 'ff9e64' },
      { token: 'string', foreground: '9ece6a' },
      { token: 'string.escape', foreground: '89ddff', fontStyle: 'bold' },
      { token: 'character', foreground: '9ece6a' },
      { token: 'preprocessor', foreground: 'e0af68' },
      { token: 'meta.preprocessor', foreground: 'e0af68' },
      { token: 'meta.preprocessor.string', foreground: '9ece6a' },
      { token: 'operator', foreground: '89ddff' },
      { token: 'delimiter', foreground: 'a9b1d6' },
      { token: 'delimiter.bracket', foreground: 'a9b1d6' },
      { token: 'delimiter.parenthesis', foreground: 'a9b1d6' },
      { token: 'namespace', foreground: '7dcfff', fontStyle: 'italic' },
      { token: 'tag', foreground: 'f7768e' },
      { token: 'attribute.name', foreground: 'bb9af7' },
      { token: 'attribute.value', foreground: '9ece6a' },
      { token: 'invalid', foreground: 'f7768e', fontStyle: 'underline' },
      { token: 'identifier', foreground: 'c0caf5' },
      { token: '', foreground: 'c0caf5' },
    ],
    colors: {
      'editor.background': '#0f1117',
      'editor.foreground': '#c0caf5',
      'editor.lineHighlightBackground': '#1a1f2b',
      'editor.selectionBackground': '#2d3548',
      'editor.selectionHighlightBackground': '#2d354860',
      'editor.wordHighlightBackground': '#363f5580',
      'editor.findMatchBackground': '#e0af6830',
      'editor.findMatchHighlightBackground': '#e0af6860',
      'editorBracketMatch.background': '#d4a57420',
      'editorBracketMatch.border': '#d4a574',
      'editorIndentGuide.background': '#1e2433',
      'editorIndentGuide.activeBackground': '#363f55',
      'editorCursor.foreground': '#d4a574',
      'editorLineNumber.foreground': '#3b4261',
      'editorLineNumber.activeForeground': '#d4a574',
      'editorError.foreground': '#f7768e',
      'editorWarning.foreground': '#e0af68',
      'editorGutter.background': '#0f1117',
      'editorWidget.background': '#1e2433',
      'editorWidget.border': '#252b3b',
      'editorSuggestWidget.background': '#1e2433',
      'editorSuggestWidget.border': '#252b3b',
      'editorSuggestWidget.selectedBackground': '#252b3b',
      'editorSuggestWidget.highlightForeground': '#d4a574',
      'editorHoverWidget.background': '#1e2433',
      'editorHoverWidget.border': '#252b3b',
      'input.background': '#141820',
      'input.border': '#252b3b',
      'input.foreground': '#c0caf5',
      'input.placeholderForeground': '#565f89',
      'scrollbar.shadow': '#00000050',
      'scrollbarSlider.background': '#252b3b80',
      'scrollbarSlider.hoverBackground': '#363f55',
      'scrollbarSlider.activeBackground': '#363f55',
      'minimap.background': '#0f1117',
      'editorOverviewRuler.border': '#1e2433',
      'editorBracketHighlight.foreground1': '#e0af68',
      'editorBracketHighlight.foreground2': '#bb9af7',
      'editorBracketHighlight.foreground3': '#7aa2f7',
      'editorBracketHighlight.foreground4': '#7dcfff',
      'editorBracketHighlight.foreground5': '#9ece6a',
      'editorBracketHighlight.foreground6': '#f7768e',
    },
  },
};
