import type { ThemeDefinition } from '../types';

export const tokyoNightTheme: ThemeDefinition = {
  id: 'tokyoNight', name: 'Tokyo Night', type: 'dark',
  colors: {
    bgDeepest: '#16161e', bgBase: '#1a1b26', bgSurface: '#1e1f2b', bgElevated: '#24283b',
    bgOverlay: '#292e42', bgHighlight: '#2f3549', bgActive: '#3b4261', bgIntense: '#414868',
    accentPrimary: '#7aa2f7', accentSecondary: '#bb9af7', accentTertiary: '#7dcfff',
    accentGlow: '#a5c4ff', accentBlue: '#7aa2f7', accentGreen: '#9ece6a', accentRed: '#f7768e',
    accentYellow: '#e0af68', accentOrange: '#ff9e64', accentPurple: '#bb9af7', accentCyan: '#7dcfff',
    accentTeal: '#73daca', accentPink: '#f7768e',
    textPrimary: '#c0caf5', textSecondary: '#a9b1d6', textMuted: '#565f89', textFaint: '#3b4261',
    textInverse: '#1a1b26',
    borderSubtle: '#292e42', borderDefault: '#2f3549', borderStrong: '#414868', borderAccent: '#7aa2f7',
    scrollbarThumb: '#2f3549', scrollbarThumbHover: '#414868', scrollbarTrack: 'transparent',
  },
  monacoTheme: {
    base: 'vs-dark', inherit: true,
    rules: [
      { token: 'comment', foreground: '565f89', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'bb9af7', fontStyle: 'bold' },
      { token: 'storage.type', foreground: '7aa2f7' },
      { token: 'type', foreground: '7dcfff' },
      { token: 'entity.name.function', foreground: '7aa2f7', fontStyle: 'bold' },
      { token: 'variable', foreground: 'c0caf5' },
      { token: 'variable.parameter', foreground: 'e0af68', fontStyle: 'italic' },
      { token: 'constant', foreground: 'ff9e64' },
      { token: 'number', foreground: 'ff9e64' },
      { token: 'string', foreground: '9ece6a' },
      { token: 'string.escape', foreground: '89ddff', fontStyle: 'bold' },
      { token: 'operator', foreground: '89ddff' },
      { token: 'preprocessor', foreground: 'e0af68' },
      { token: 'delimiter', foreground: 'a9b1d6' },
      { token: 'namespace', foreground: '7dcfff', fontStyle: 'italic' },
      { token: 'identifier', foreground: 'c0caf5' },
      { token: '', foreground: 'c0caf5' },
    ],
    colors: {
      'editor.background': '#1a1b26', 'editor.foreground': '#c0caf5',
      'editor.lineHighlightBackground': '#24283b', 'editor.selectionBackground': '#3b4261',
      'editorCursor.foreground': '#c0caf5', 'editorLineNumber.foreground': '#3b4261',
      'editorLineNumber.activeForeground': '#c0caf5',
      'editorWidget.background': '#292e42', 'editorWidget.border': '#2f3549',
      'input.background': '#1e1f2b', 'input.border': '#2f3549', 'input.foreground': '#c0caf5',
      'editorBracketHighlight.foreground1': '#e0af68',
      'editorBracketHighlight.foreground2': '#bb9af7',
      'editorBracketHighlight.foreground3': '#7aa2f7',
      'editorBracketHighlight.foreground4': '#7dcfff',
      'editorBracketHighlight.foreground5': '#9ece6a',
      'editorBracketHighlight.foreground6': '#f7768e',
    },
  },
};
